name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan \
          -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}"
