name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      #  Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      #  Azure credentials as environment variables
      - name: Set Azure credentials
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      # Terraform Init
      - name: Terraform Init
        run: terraform -chdir=./terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=./terraform plan -out=tfplan

      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=./terraform apply -auto-approve tfplan
