name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login to Azure using SP credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: >
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Terraform Init
      - name: Terraform Init
        run: terraform -chdir=./terraform init

      #  Terraform Validate
      - name: Terraform Validate
        run: terraform -chdir=./terraform validate

      #  Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=./terraform plan -out=tfplan \
          -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      # Terraform Apply 
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=./terraform apply -auto-approve tfplan \
          -var "ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
